import type { Metadata } from "next";
import { LegalPage, CONTACT_EMAIL } from "@/components/legal/LegalPage";
export const metadata: Metadata = { title: "Terms of Service | Asrii Automate", description: "These terms cover use of Asrii Automate, an Instagram workflow automation application operated by Asrith Kulukuri. By using the service, you agree to these terms." };
export default function Page() { return <LegalPage title="Terms of Service" introduction="These terms cover use of Asrii Automate, an Instagram workflow automation application operated by Asrith Kulukuri. By using the service, you agree to these terms."><section><h2>1. Service and testing status</h2><p>Asrii Automate lets authorized users connect an Instagram Professional account, configure comment-based workflows, and generate private replies through Meta APIs. It also provides simulated tests and execution logs. The application is currently an experimental testing service. Features may change, fail, or be unavailable.</p><p>Prices and offers in sample workflows are demonstration content, not a purchase agreement or subscription charge.</p></section>
<section><h2>2. Account access and authorization</h2><p>Connect only accounts you own or are authorized to manage. You are responsible for the permissions you grant, your credentials, and activity initiated through your workflows. Do not enter passwords or access tokens in public messages or workflow templates. Access is limited by Meta account eligibility, permissions, and platform availability.</p></section>
<section><h2>3. Acceptable use</h2><p>Use the service lawfully and comply with applicable Meta and Instagram terms. Do not use it for spam, harassment, impersonation, unauthorized access, misleading messages, or attempts to bypass platform restrictions. You are responsible for the content and links you configure and the rights needed to use them.</p></section>
<section><h2>4. Mock and live execution</h2><p>Mock mode simulates replies without sending Instagram messages. Live mode can send real messages when enabled and when an active workflow matches an incoming event. Review the connected account, triggers, and message template before activating a workflow. Disable workflows when you no longer want them to run.</p><p>We do not guarantee message delivery, response times, continuous availability, or approval by Meta. API permissions, rate limits, token expiration, and platform changes can affect operation.</p></section>
<section><h2>5. Data and service providers</h2><p>Our <a href="/privacy">Privacy Policy</a> describes data processing. Our <a href="/data-deletion">Data Deletion Instructions</a> explain how to stop automation and request removal. Meta, Supabase, and Vercel operate services used by the application and have their own applicable terms.</p></section>
<section><h2>6. Suspension and ending use</h2><p>You may stop using the service, pause workflows, disconnect Instagram, and request deletion. We may restrict access to investigate misuse, protect accounts, comply with applicable requirements, or discontinue the testing service.</p></section>
<section><h2>7. Service limitations</h2><p>The testing service is provided as available without a promise that it is error-free or suitable for a particular purpose. To the extent permitted by applicable law, we disclaim warranties and liability for indirect or consequential losses. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded.</p></section>
<section><h2>8. Changes and contact</h2><p>Changes will be posted here with an updated date. For questions about these terms, contact <a href={"mailto:" + CONTACT_EMAIL}>{CONTACT_EMAIL}</a>.</p><p>Asrii Automate is an independent application and is not endorsed by Meta or Instagram.</p></section></LegalPage>; }
