import type { Metadata } from "next";
import { LegalPage, CONTACT_EMAIL } from "@/components/legal/LegalPage";
export const metadata: Metadata = { title: "Privacy Policy | Asrii Automate", description: "This policy describes how Asrii Automate, operated by Asrith Kulukuri, handles information in its current testing service. Contact us using the email below for privacy questions or deletion requests." };
export default function Page() { return <LegalPage title="Privacy Policy" introduction="This policy describes how Asrii Automate, operated by Asrith Kulukuri, handles information in its current testing service. Contact us using the email below for privacy questions or deletion requests."><section><h2>1. Information processed</h2><ul><li>Workspace and application user records, including names, email addresses, membership information, and account identifiers where provided.</li><li>Connected Instagram account identifiers, usernames, profile information where returned, permission information, and encrypted access tokens.</li><li>Incoming webhook data, including comment text, usernames, commenter identifiers, media and comment identifiers, and event timestamps.</li><li>Workflow settings, reply templates, generated or sent messages, delivery identifiers, execution results, errors, and audit history.</li><li>Session cookies and technical request information used to operate, secure, and troubleshoot the service. Hosting providers may also maintain infrastructure logs.</li></ul><p>Mock tests and sample workspaces can contain fabricated data. Real comments and connected-account information are processed when you enable the corresponding integration.</p></section>
<section><h2>2. Why we use information</h2><p>We use this information to connect authorized Instagram accounts, match comments against configured workflows, send authorized replies, display activity, diagnose failures, and respond to support or deletion requests. The application uses a session cookie to recognize a browser session.</p></section>
<section><h2>3. Providers and sharing</h2><p>Meta receives API requests needed for account access and message delivery. Supabase hosts the application database, and Vercel hosts the application and processes requests. Information needed to operate these services is processed by those providers. Depending on their infrastructure, processing may occur outside your country.</p><p>We do not sell personal information or use Instagram data from this application for advertising. We may disclose information where required by applicable law or necessary to investigate abuse and protect the service.</p></section>
<section><h2>4. Storage and protection</h2><p>Instagram access tokens are encrypted before database storage. The deployed application uses HTTPS. These measures do not eliminate every risk. The current testing build uses simplified demo workspace access rather than a completed production authentication system; use it only with authorized test accounts and test content.</p></section>
<section><h2>5. Retention</h2><p>Connected-account records are retained until disconnected or removed. Workflow, comment, execution, message, and audit records may remain after disconnection. The current application does not automatically expire these records; they remain until manually removed or a verified deletion request is completed. Provider logs and backups, if maintained, follow their respective retention cycles.</p></section>
<section><h2>6. Your choices</h2><p>You can pause workflows, disconnect Instagram, revoke the app’s access through Meta or Instagram, and request access, correction, or deletion by emailing <a href={"mailto:" + CONTACT_EMAIL}>{CONTACT_EMAIL}</a>. We may verify your authority before fulfilling a request. Applicable rights depend on your location.</p><p>See <a href="/data-deletion">Data Deletion Instructions</a> for the request process, including requests from people who commented on a connected account’s content.</p></section>
<section><h2>7. Changes and contact</h2><p>Updates are posted on this page with a revised date. Contact Asrith Kulukuri at <a href={"mailto:" + CONTACT_EMAIL}>{CONTACT_EMAIL}</a> with questions about this policy.</p></section></LegalPage>; }
